#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <myapp_icons.h>

int32_t myapp_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm myapp!");

    return 0;
}
